# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

findInterval2 <- function(x, breaks) {
    .Call('_xQTLstats_findInterval2', PACKAGE = 'xQTLstats', x, breaks)
}

smoothQTL <- function(G, Map, Kern, W) {
    .Call('_xQTLstats_smoothQTL', PACKAGE = 'xQTLstats', G, Map, Kern, W)
}

